### ISSUE TITLE
Testing "issues", because why not...

### ISSUE THREAD

**Issue by Yubelious** [Skeletonxf/dueling-nexus-split-view#2]
An issue I noticed today is that, although "url-prefix" worked in another style, I find myself unable to incorporate it into this one to affect only the "/game/..." pages. This is important because the style as it is currently also affects the home page, most notibly with the font resize. Ideally, I would like this style to affect both "/game/..." and "/editor/..." (but not "/game" and "/editor"), if only for the sake of uniformity. This is only a minor issue and shouldn't dramatically affect larger resolutions, given a font size increase of only 2 pixels, if I remember correctly (this was a few hours ago). However, this is quite noticable with smaller resolutions where the lesser starting font size is significantly noticable. My former attempt to seperate the 2 affected pages with a comma (,) some time ago had failed and therefore was abandoned, however, in light of this minor visual issue, it may be wise to once again atempt styling 2 specific pages with one code. 

_Sent from my Samsung SGH-I337M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Skeletonxf** [comment]
Aaaah. Can't you just use `@-moz-document domain("duelingnexus.com") {` for styles to affect everything and then use a more specific stylish such as 

```css
@-moz-document url("https://github.com/Skeletonxf/dueling-nexus-split-view/issues/2") {

}
```

for when you want to target specific urls, or target the exceptions to undo the changes by the more general css?

**Comment by Yubelious** [comment]
This would work, for example, in the case of 
*@-moz-document url("https://duelingnexus.com/editor/") {background:none !important;}*
Since this only affects the page with the list of decks (if that) and not the many pages that store the decks themselves. Every deck, and more importantly every duel, has its own individual link. I did it before. I just gotta figure out how. It probably worked because it was in the middle of a 3-part code, each affecting specific places.

_Sent from my Samsung SGH-I337M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Yubelious** [comment]
Oh, sure. Today it works. [http://media0.giphy.com/media/12wPElEkteoJUY/giphy.gif](url)

It moved the card search down to where to chat it, but I'm actually okay with that. Testing on other browsers, then updating.
